name: Bug report
description: File a bug
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      placeholder: "Describe the issue..."
    validations:
      required: true
