name: Feature request
description: Suggest an improvement for SecurePipe
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve SecurePipe! Please fill out the sections below so we can understand your idea.
  - type: textarea
    id: problem
    attributes:
      label: "What problem are you trying to solve?"
      description: "Describe the workflow or scenario that could be improved."
      placeholder: "When I try to..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: "Describe the proposed solution"
      description: "Share the feature or change you would like to see."
      placeholder: "It would help if SecurePipe could..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Additional context"
      description: "List any alternatives you've considered, related issues, or other context."
      placeholder: "I've also considered..."
